### PR TITLE
Issue142 Solve tower of hanoi

### LINKED ISSUE #142: Add the solve operation to the TowerOfHanoi.py visualization
A new operation, Solve, should be added to the TowerOfHanoi visualization.  The button should be enabled whenever all disks are stacked on the left spindle (as they are after a New operation).

The code and highlights in the code should be displayed for both the New and Solve operations.  The latter should show the recursive invocations of the `solve()` method of the `TowerOfHanoi` class.  

The textbook code is shown below.  Print statements do not need to be animated.
```
class TowerOfHanoi(object):    # Model the tower on 3 spindles using
                               # 3 stacks
   def __init__(self, nDisks=3): # Constructor w/ starting number of
      self.__stacks = [None] * 3 # Stacks of disks
      self.__labels = ['L', 'M', 'R'] # Labels for stacks/spindles
      self.__nDisks = nDisks   # Total number of disks
      self.reset()

   def reset(self):            # Initialize state of puzzle
      for spindle in range(3): # Set up each of 3 spindles
         self.__stacks[spindle] = Stack( # Start w/ empty stack
            self.__nDisks)     # that can hold all the disks
         if spindle == 0:      # On the first spindle,
            for disk in range( # push the disks on the stack
                  self.__nDisks, 0, -1): # in descending order of size
               self.__stacks[spindle].push(disk)

   def label(self, spindle):   # Get the label of spindle
      return self.__labels[spindle]

   def height(self, spindle):  # Get the number of disks on a spindle
      return len(self.__stacks[spindle])

   def topDisk(self, spindle): # Get top disk number on a spindle or
      if not self.__stacks[spindle].isEmpty(): # None if no disks
         return self.__stacks[spindle].peek() # Peek at top disk

   def __str__(self):          # Show puzzle state as a string
      result = ""              # Start with empty string
      for spindle in range(3): # Loop over spindles
         if len(result) > 0:   # After first spindle,
            result += "\n"     # separate stacks on new lines
         result += (
            self.label(spindle) + ': ' + # Add spindle label
            str(self.__stacks[spindle])) # and spindle contents
      return result

   def move(self, source, to,  # Move a single disk from source
            show=False):       # spindle to another, possibly printing
      if self.__stacks[source].isEmpty(): # Source spindle must have
         raise Exception(      # a disk, or it's an error
            "Cannot move from empty spindle " + self.label(source))
      if (not self.__stacks[to].isEmpty() and # Destination cannot
          self.topDisk(source) > # have a disk smaller than that of
          self.topDisk(to)):   # source
         raise Exception(
            "Cannot move disk " + str(self.topDisk(source)) +
            "on top of disk " + str(self.topDisk(to)))
      self.__stacks[to].push(  # Push top disk of source spindle
         self.__stacks[source].pop()) # on to the 'to' spindle
      if show:
         print('Move disk', self.topDisk(to),
               'from spindle', self.label(source),
               'to', self.label(to))

   def solve(self,             # Solve the puzzle to move
             nDisks=None,      # N disks from
             start=0,          # starting spindle
             goal=2,           # to goal spindle
             spare=1,          # with spare spindle
             show=False):      # and possibly showing steps
      if nDisks is None:       # Default number of disks to move
         nDisks = self.height(start) # is all the disks on start
      if nDisks <= 0:          # If no request to move disks
         return                # there's nothing to do
      if self.height(start) < nDisks: # Check if there are fewer
         raise Exception(             # disks to move than requested
            "Not enough disks (" + str(nDisks) +
            ") on starting spindle " + self.label(start))

      self.solve(nDisks - 1,  # Move n - 1 from start to spare with
                 start, spare, goal, show) # goal as spare
      self.move(start, goal, show)  # Move nth from start to goal
      if show: print(self)          # Show puzzle state after move
      self.solve(nDisks - 1,  # Then move n - 1 from spare to goal
                 spare, goal, start, show) # with start as spare
      if (nDisks == self.__nDisks and   # Were all disks moved?
          show):              # then puzzle is solved and can show
         print("Puzzle complete") # conclusion if requested
```

### PR DESCRIPTION
**Pull request by JMCanning78**
This pull request implements the automated solver of the Tower of Hanoi puzzle to close #142.  It adds some capabilities to the call stack to better show the changes that occur during recursive calls.  

There's still a bug if you stop the animation of the solution, move the disks back to the starting spindle, and then try to auto-solve.  I'll document that separately.

### CODE REVIEW

**Comment by JMCanning78** [comment]
Pushed commit 2700822 to fix and close #147.

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This is awesome! A couple of thoughts/feedback:

1. The leftmost spindle looks to be cut off sometimes. I notice this when pressing new. Here is what it looks like for me
image

2. It might be nice to see the disks in different colors

3. The code highlighting (specifically for `solve`) and the scroll that follows the code is great. It is a bit confusing that the calls look identical. It might be interesting to see the changed `nDisk` reflected in each code block. Alternatively, it might be interesting to see a stack that holds the recursive calls. That may be a lot more work though.

**Comment by JMCanning78** [comment]
Commit 33bdaa7 should fix items 1 and 3 in [your comment](https://github.com/JMCanning78/datastructures-visualization/pull/146#pullrequestreview-511314303), Lily.  Specifically, I fixed the New command to first draw all 3 spindles at their full length before adding the disks to the left hand spindle.  I also changed what's shown in the code box to include the arguments passed to each of the method calls.  That adds a bit of detail that distinguishes the calls on the stack.

I merged in the changes from `origin/master` which allows the code text box to be resized properly.

As for item 2, I think coloring the disks can be another issue.

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
The changes you made look good! 

I'm noticing that the spindles occasionally appear to be missing the end when a disk is moved. Here is a picture of what it looks like for me:
image

**Comment by JMCanning78** [comment]
Commit 4035f1f should fix the spindle appearance bug you mentioned in [your comment](https://github.com/JMCanning78/datastructures-visualization/pull/146#pullrequestreview-512014592), Lily.  I also made changes in commit 7abf558 that should close #152 by assigning different colors to each disk.

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This looks great! The colors were great choices and it looks nice that the top is lighter than the bottom.

As you mentioned in the comments in commit 7abf55868d0ee5a57cc7a02a8afcc8246b681ef0, there is a bug when the user presses stop while a disk is moving. The disk continues to move down the spindle past the other disks and then jumps back to the top of the pile of disks.

**Comment by JMCanning78** [comment]
I went ahead and approved and merged this PR.  If you can reproduce a bug sequence reliably, add it to Issue #155 or make a new issue for it.

**Pull request merged**
