### PR TITLE
Issue101 Add sorted linked lists and traverse operation

### PR DESCRIPTION
**Pull request by JMCanning78**
This PR closes Issue #101 to add sorted lists to the LinkedList.py app.  It also closes issue #140 which also asked for a traverse operation.

### CODE REVIEW

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This looks great! Three thoughts:
1. The delete functionality when the list is sorted does not match the textbook code. According to the textbook code, the delete function should stop searching for the item if it has passed `goal`. The search button does seem to implement this properly for sorted LinkedLists.

2. The newLink arrow seems to be cut off on my screen.
image

3. It is not clear to the average user that the sorted LinkedList is dealing with strings had the user initially started by inserting numbers. This may be mentioned in the textbook when explaining the animations, in which case this comment is irrelevant.

**Comment by JMCanning78** [comment]
In commit 021d72d, I fixed the bug where deleting a non-existent item from a sorted list hand the pointers traversing the whole list.  That was mentioned as item no. 1 of [your review above](https://github.com/JMCanning78/datastructures-visualization/pull/149#pullrequestreview-507916240)

To fix item no. 2 in the review and a whole bunch of other text position issues, I added some new methods to VisualizationApp to calculate the width and height of a string when drawn by Tk in a particular font.  I made all the font sizes negative numbers.  That tells Tk to size the font in pixels as opposed to points.  I found that specifying the size in points performs identically on Windows and macOS (whereas they appear differently when using points).  This approach should make it easier for developers to develop on either platform and have it work properly on both.  I haven't tested on Linux or other platforms.

Regarding item no. 3, yes the ordering will be confusing to users that only enter numbers.  Since we don't have a convenient place to put help for each app (yet), I'll explain the behavior in the text.

In commit ccf5d1b, I fixed the startAngle in SimpleSorting Issue #150.

I also changed LinkedList.py to remove the "link" pointer when it animates the removal of a `Link` from the list.  That's a slightly different behavior than other visualization apps where all the local variables remain visible after the operation completes.  In this case, leaving the "link" pointer visible means that it would point at a `Link` on the canvas that it doesn't point to in the program.  It's probably more accurate to have it stay on the canvas pointing to the deleted `Link` but it was easier to just add it to the list of items moving off the canvas.

@lilypolonetsky, could you try running the LinkedList.py and a few of the other apps to see that the text items are being displayed in reasonable sizes and positions on your (Windows) screen?

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
I noticed a new thing about the linked list unrelated to my previous comments. It seems that traverse still runs if the list is empty. The picture below shows that. Perhaps an error should just be shown?
image

Otherwise, the visualization looks great! I've attached pictures of what the animation looks like on my screen in the comments. The arrows look much better.

The delete functionality for a sorted linkedlist has been fixed.

**Comment by lilypolonetsky** [comment]
image
image

**Comment by lilypolonetsky** [comment]
image
image

**Comment by JMCanning78** [comment]
It's not really an error to traverse an empty data structure, but it is confusing to not see anything happen in response to pressing an operation button.  I added a message when the list is empty in a traverse operation (in commit 2032854).

Thanks for the screenshots.  I think these changes will help eliminate the need to check the appearance  in the different implementations.

**Review by lilypolonetsky — APPROVED** [review]
This looks great!

**Pull request merged**
