### PR TITLE
Issue99 Highlight text entries and enable operation re-run

### LINKED ISSUE #99: Add methods to highlight the text entry widgets for arguments
Some of the more complex data structures use multiple input arguments for some operations.  See the Bloom filter for an example.  When errors occur, the single status/error message provided by VisualizationApp may not be sufficient to explain which of the arguments has caused the problem.

Add a `setArgumentHighlight(self, index, color=None)` method to `VisualizationApp`.  This will be called by visualization modules to change the background color of the text entry widget to a color different than its normal background color, or to restore the normal background when `color` is `None`.  Define a constant in VisualizationApp for ERROR_HIGHLIGHT with a pale red or pink color from the Tk palette that can be the standard color for errors.

Add an event handler to all the text entry widgets that calls `setArgumentHighlight()` to restore the normal background color to a widget when the user changes the text.  This should make the highlight go away when users start to fix entries that caused problems.  They will get re-highlighted the next time an error is found.

Change the BloomFilter.py program to use the `setArgumentHighlight()` to highlight each of the arguments causing problems when operations are invoked.  The error message plus the highlighting should make it clearer what needs to be corrected by the user before trying again.  Note if all the arguments are valid for the New Bloom filter operation, but it would take more bits to represent the filter than fit on the canvas, don't highlight any of the arguments, since it's the combination of the three that determines the number of bits needed.

### PR DESCRIPTION
**Pull request by JMCanning78**
This PR closes #99 by creating a facility to highlight text entry widgets with a background color to indicate a problem with their value.  It's most useful for visualization apps like BloomFilter where there are multiple arguments to an operation.  The highlighting helps identify where the problems are.

As a slightly related consequence, it's frequently useful to re-run the last command after typing some text in one of the text entry widgets, perhaps after correcting an error.  This PR creates a facility in VisualizationApp that records the last operation run that required arguments.  Then when return or enter is typed in a text entry widget, it re-runs that operation.  Creating this facility required using a specialized button (a ttk.Button) which in turn required changing the API for how button states are queried and changed.    Once this PR gets merged to `master`, we will need to fix any lingering usage of the old API.

### CODE REVIEW

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This is really cool! 

Pressing enter to run the last operation worked great for me.

I found an unexpected behavior with the textbox highlighting (not sure if it qualifies as a bug). When I enter invalid input into a box that is necessary for the new hash, it highlights the invalid input. However, when I press insert with the invalid input still present (but not necessary for the insert button), the textbox remains highlighted in red.

**Comment by JMCanning78** [comment]
I fixed the bug you mentioned in [your comment](https://github.com/JMCanning78/datastructures-visualization/pull/151#pullrequestreview-513814240) where the inputs remain highlighted even if cleared by another operation (eg. an Insert after a failed New operation).  That's in commit 9469143.

I also added a behavior that highlights the bits that are already set when inserting a new key in the Bloom filter.  The highlights are temporary; they are erased on the next operation.  Together with the new feature of being able to edit the entry text and hit return to repeat the operation, you can fill the Bloom filter quite quickly by modifying the last inserted key by one or two characters and hitting return.

I also made

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
The bug that I mentioned in my original comment is almost fixed. It may be that this is the intended sequence for clearing the box but the sequence of clearing the red box was confusing to me.

For example, if I do the following: 
1. put in an invalid false positive probability, fill out the other two boxes with valid input
2. click new
3. click insert
The false positive probability box stays highlighted red until the end of the hash animation and only then is it cleared. I think it would make more sense to clear the red highlight before the hash since that textbox was not needed for the insert. I presume this is related to the fact that clear is only called after the animation is complete.

**Comment by JMCanning78** [comment]
Clearing the unused arguments makes sense.  I implemented that in commit f6afce9.  Ready for review (again)

**Review by lilypolonetsky — DISMISSED** [review]
Looks great!

**Pull request merged**
