### PR TITLE
Issue105 create avl tree

### PR DESCRIPTION
**Pull request by lilypolonetsky**
As per issue #105, I implemented new tree, random fill, and insert for the AVL tree.

While the nodes move with the rotation, I struggled to make the lines move with the rotation. If anybody has any thoughts on how to make it work, I would love to hear,

### CODE REVIEW

**Review by JMCanning78 — CHANGES_REQUESTED** [review]
Good start, but I'm seeing bugs.  I added the ability to take command line arguments as a sequence to be inserted in commit 3e963ef.  That makes it easier to reproduce bugs.  Here's a transcript of using the command line to cause an error:
```
python3 AVLTree.py 33 11 55 44 47 45
Traceback (most recent call last):
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 188, in <module>
    tree.clickInsert()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 158, in clickInsert
    self.insert(val)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 44, in insert
    root, flag = self.__insert(self.getRoot(), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 100, in __insert
    self.setRightChild(node, self.rotateRight(rightChild, animation= animation))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 593, in rotateRight
    self.restoreNodesPosition([toRaise] + self.getAllDescendants(toRaise), sleepTime=.05)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 347, in restoreNodesPosition
    node.coords = self.calculateCoordinates(self.getParent(node), self.getLevel(node), self.getChildDirection(node))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 284, in calculateCoordinates
    return parent.coords[0] + 1/2**(level+1)* self.TREE_WIDTH, self.ROOT_Y0+level* self.LEVEL_GAP
AttributeError: 'NoneType' object has no attribute 'coords'
```

I also stumbled on an infinite recursion bug, but I don't have procedure for reproducing the error.  Here's the transcript anyway:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/VisualizationApp.py", line 413, in animatedOperation
    command()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 176, in <lambda>
    "Insert", lambda: self.clickInsert(), numArguments=1,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 157, in clickInsert
    self.insert(val)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 43, in insert
    root, flag = self.__insert(self.getRoot(), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 88, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 70, in __insert
    newLeft, flag = self.__insert(self.getLeftChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 75, in __insert
    self.redrawLines()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 382, in redrawLines
    self.drawAllLines()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 369, in drawAllLines
    self.__drawLines(left, right)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
```
which keeps repeating until finally it gets to:
```
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 377, in __drawLines
    self.__drawLines(self.getLeftChild(right), self.getRightChild(right))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 374, in __drawLines
    self.__drawLines(self.getLeftChild(left), self.getRightChild(left))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 376, in __drawLines
    self.createLine(right)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 356, in createLine
    line = self.canvas.create_line(*lineCoords, tags = ("line", node.tag + " line"))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 2791, in create_line
    return self._create('line', args, kw)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 2775, in _create
    *(args + self._options(cnf, kw))))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1464, in _options
    cnf = _cnfmerge((cnf, kw))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 105, in _cnfmerge
    elif isinstance(cnfs, (type(None), str)):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

**Comment by lilypolonetsky** [comment]
Commit 97e9662 addresses @JMCanning78's bug mentioned above. The issue was that extra nodes were lingering in the array even after being moved. The changes made here remove all the nodes to the right/left (depending on which way the rotation is) and puts them back into the correct place in the array.

While not certain, I believe this would also address the endless recursion bug @JMCanning78 mentioned. My bet is that it was probably due to a node not being deleted and having it in the array twice. The drawing mechanisms probably got confused (for lack of a better terminology) about which node and its children to follow

**Review by JMCanning78 — CHANGES_REQUESTED** [review]
Still getting errors, this time when the tree reaches depth 3 or 4, but only in some positions.  Here are some examples.  The first is just with the numbers 1 through 17 increasing.
```
python3 AVLTree.py 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
Traceback (most recent call last):
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 188, in <module>
    tree.clickInsert()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 158, in clickInsert
    self.insert(val)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 44, in insert
    root, flag = self.__insert(self.getRoot(), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 89, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 89, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 89, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  [Previous line repeated 1 more time]
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 93, in __insert
    self.restoreNodesPosition([newRight], sleepTime=.01)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 347, in restoreNodesPosition
    node.coords = self.calculateCoordinates(self.getParent(node), self.getLevel(node), self.getChildDirection(node))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 282, in calculateCoordinates
    return parent.coords[0] - 1/2**(level+1)* self.TREE_WIDTH, self.ROOT_Y0+level* self.LEVEL_GAP
AttributeError: 'NoneType' object has no attribute 'coords'
```

This one shows an error before the tree fills up:
```
python3 AVLTree.py 1 11 9 6 7 4 3 
Traceback (most recent call last):
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 188, in <module>
    tree.clickInsert()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 158, in clickInsert
    self.insert(val)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 44, in insert
    root, flag = self.__insert(self.getRoot(), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 71, in __insert
    newLeft, flag = self.__insert(self.getLeftChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 100, in __insert
    self.setRightChild(node, self.rotateRight(rightChild, animation= animation))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 623, in rotateRight
    self.restoreNodesPosition([toRaise] + self.getAllDescendants(toRaise), sleepTime=.05)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 347, in restoreNodesPosition
    node.coords = self.calculateCoordinates(self.getParent(node), self.getLevel(node), self.getChildDirection(node))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 284, in calculateCoordinates
    return parent.coords[0] + 1/2**(level+1)* self.TREE_WIDTH, self.ROOT_Y0+level* self.LEVEL_GAP
AttributeError: 'NoneType' object has no attribute 'coords'
```

I added  commit 8e51eaf to make it easier to insert more items after the command line ones are inserted.

**Comment by lilypolonetsky** [comment]
Great catches! Thanks for catching these.

Commit e03d124 addresses the second case you posted about. Similar to before, descendants of the nodes that were being moved were lingering behind so there were duplicates in the nodes array

**Comment by JMCanning78** [comment]
OK but the other test case, `python3 AVLTree.py 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17` still raises an exception.  I can also get it to happen (faster) with the following procedure:
1. Run `python3 AVLTree.py`
2. Enter 15 in the text entry box and select Random Fill
3. Choose a new value to insert that would initially go at level 5 (beyond where the tree can display).  Select Insert.  That's when I get a stack trace ending with:

```
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 71, in __insert
    newLeft, flag = self.__insert(self.getLeftChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 71, in __insert
    newLeft, flag = self.__insert(self.getLeftChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 89, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 89, in __insert
    newRight, flag = self.__insert(self.getRightChild(node), key, animation=animation)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 93, in __insert
    self.restoreNodesPosition([newRight], sleepTime=.01)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 347, in restoreNodesPosition
    node.coords = self.calculateCoordinates(self.getParent(node), self.getLevel(node), self.getChildDirection(node))
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/BinaryTreeBase.py", line 282, in calculateCoordinates
    return parent.coords[0] - 1/2**(level+1)* self.TREE_WIDTH, self.ROOT_Y0+level* self.LEVEL_GAP
AttributeError: 'NoneType' object has no attribute 'coords'
```
 
If in step 3, the user chooses a value that would go at level 4, it inserts correctly.  I haven't looked at the code, but I'm guessing there is something happening when nodes would be placed off the canvas.  

A completely separate bug: when I run Random Fill with N as the value on an empty tree, I expect to see N nodes inserted in the tree.  Instead, it seems somewhat random how many nodes show up.  For example, in the procedure above when I insert 15 random nodes in step 2, I usually end up with 27.  It should insert the requested number of unique values.

**Comment by JMCanning78** [comment]
I looked (very briefly) at the code.  There's a fixed size array of nodes allocated for empty trees in BinaryTreeBase.py that is probably the reason:
```
    def emptyTree(self):
        self.canvas.delete("all")
        self.size = 0
        self.nodes = [None] * (2**self.MAX_LEVEL)
```
MAX_LEVEL defaults to 5, so only 32 nodes can be entered.  That's all that fit easily on the canvas, but the code needs to do checks and avoid operations that would go past that limit.

**Comment by lilypolonetsky** [comment]
I'm working on the bug involving nodes going below the max level. My thought is to expand the array to allow it to place something briefly below the max level and then rotate. I should have something soon. In terms of the random fill - I'll take a look and see what I find

**Comment by lilypolonetsky** [comment]
I just took a look at the randomFill issue and I think this should be resolved in the next commit I do. The `clearDescendants` method was not passing the default `subSize` param so it was decrementing the size incorrectly

**Comment by lilypolonetsky** [comment]
These new commits should fix the fill issue, animate the insertion point with an arrow, and stop insertions from occurring past the max level.

The arrow moves back up after an insertion to show the recursion unwinding

**Review by JMCanning78 — CHANGES_REQUESTED** [review]
Commit ddea152 has fixed the error when running `python3 AVLTree.py 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17`.  The error message says "Cannot insert at level 6 or below".   The root is level 0 and that makes the lowest visible level 4.  The error message should say "Cannot insert at level 5 or below" or  maybe ""Cannot insert below level 4" for brevity.

When inserting new items, the animation doesn't show how the insertion point is found as it descends the tree, comparing keys.  The animation should show that search process, following the textbook code's recursive descent of the `node` parameter of `__insert()`.

New error: "local variable `arrow` referenced before asssignment" happens after the following procedure:

1. Enter 1 in text entry box
2. Select Random Fill

This produces:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/VisualizationApp.py", line 413, in animatedOperation
    command()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 195, in <lambda>
    "Random Fill", lambda: self.clickRandomFill(), numArguments=1,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 186, in clickRandomFill
    self.randomFill(val)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 36, in randomFill
    self.insert(nums.pop(), animation=False)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AVLTree.py", line 50, in insert
    root, flag = self.__insert(self.getRoot(), key, animation=animation, arrow=arrow)
UnboundLocalError: local variable 'arrow' referenced before assignment
```

**Comment by JMCanning78** [comment]
Commit 4ede219 added a pretty thorough test program (in the Test Results subdirectory).  Using that to test the insert operation shows no errors.  I've also run BinaryTree.py and Heap.py to test the changes to BinaryTreeBase.py, and I think everything is working properly.

**Pull request merged**
