### PR TITLE
added initial instructions to text entry

### PR DESCRIPTION
**Pull request by lilypolonetsky**
The hint text is only visible until someone clicks into the box.

I changed maxArgWidth so that the instructions would not be cut off

### CODE REVIEW

**Comment by JMCanning78** [comment]
Thanks, Lily.  That's a pretty good way to get the help text displayed.
I think it would be better, however, to use a Label widget that obscures the text entry widget.  That prevents any code from reading the value in the Entry widget and finding it to be unusable.   I made some changes in the issue branch to implement it with a Label.  Try it out and see what you think. 
One thing I noticed about using the Label, after clicking it to make it disappear, it doesn't put the keyboard focus on the Entry widget below it.  That would be nice to have.  Also, I made the font size larger for the Label to try to completely cover the Entry widget below it.  I don't think it does that.  Is your development environment on Windows?  I'd be interested to know how it looks on Windows.

**Comment by JMCanning78** [comment]
Another benefit to using the overlaid Label is that the maxArgWidth parameter can remain what is needed for actual arguments.

**Comment by lilypolonetsky** [comment]
Here is how it looks for me 
image

To me, it looks a bit confusing. It does not say "click here" but instead says "Enter number here" and the entry box is not visible. As a user, I would not think to click there and would not understand why it was telling me to enter a number there.

I do appreciate that `maxArgWidth` does not need to be changed.

One option to my concern would be to change the text to say "click to enter number."

I do think there may be a benefit to leaving the entry box visible and having the initial instructions lay on top of the entry box similar to my approach. I think my approach deals with the concern that the code may read the value in the entry widget and find it to be unusable because it does not allow the value to be read until the initial text is deleted.

Let me know what you think about my observations.

**Comment by JMCanning78** [comment]
Those are good suggestions.   I like the wording change to "Click to enter number" when it covers the text entry widget.   If we do place the label above or below the text entry area, we could phrase it as "Enter number here" and add a handler to the text entry area that makes the label disappear when users first enter a value.
The one odd thing I can think of is when the number of text entry areas (one or two) is equal to or one more than the number of operation buttons in the column, we'll have to add some rows for the labels.  When the labels are dismissed, the operations box will shrink vertically, which might be unsettling.  It's worth trying and seeing what works well.
Would you like to try those changes or shall I make a separate issue that someone else can work?

**Comment by JMCanning78** [comment]
I went ahead and made the changes discussed above.  Here are my notes from the commit:

> This changes how a helpText label is created for the text entry widgets and how it is removed by clicking on it or putting keyboard focus on one of the text entry widgets.  The label is placed below all the text entry widgets, and it only allows one label for all text entries.
> 
> A test program was added to the Test Results directory to see how the layout of buttons progresses with each call to addOperation().

The test program in "Test results" makes use of a symbolic link to VisualizationApp.py in the parent directory.  That is supposed to work in git.  I know it works on macOS and Linux, but I need to try it on Windows to verify it works there too.

**Comment by JMCanning78** [comment]
I noticed while testing on Windows that the fonts and button appearances are quite different from what I see on macOS.  After several iterations testing on both platforms, I think I have settings that are reasonable in both.  In particular, the HINT_FONT is now based on the CONTROLS_FONT, and that font is now used for button labels and the text entry widget.

@lilypolonetsky, would you please re-review the PR branch and see if it needs changes?  Note that if you want to run the testMultipleButtons.py, you'll need to copy it up to the PythonVisualizations directory and run it there (or go through all the procedures above for getting symlinks to work on Windows with git).

**Pull request merged**
