### PR TITLE
update Array.py

### PR DESCRIPTION
**Pull request by shirapahmer**
Resolves Array.py aspect of issue 12. Animates the removal of the right most tile of the array

### CODE REVIEW

**Comment by shirapahmer** [comment]
We noticed an error with the deleteRightmost button that if it is pressed multiple times in a row, it seems that the message threads in the program interrupt each other and the cells are deleted in a LIFO order. This can be dealt with by disabling the deleteRightmost button each time it is pressed until the operation is complete

**Comment by JMCanning78** [comment]
@shirapahmer 's comment (https://github.com/JMCanning78/datastructures-visualization/pull/37#issuecomment-646070906) points out an interesting  behavior.  The animation of the most recent deleteRightmost request takes precedence.  Once the value has been moved off the canvas, Array.py resumes animating the removal of the older requests. 
I think it's fine to leave that behavior in the program.  I don't think it's an error; just an indication that the user is impatient ;->
When the play/pause/stop buttons are added, however, we should see what happens when the user launches several deleteRightmost animations and then clicks Stop before they complete.

**Comment by JMCanning78** [comment]
@miriamrabinovich and @shirapahmer could you please try the merge process that I reviewed yesterday and follow-up on  https://github.com/JMCanning78/datastructures-visualization/pull/37#pullrequestreview-437694134 above?  Specifically, merge `origin/master` into  `issue12-Array-deleteRightmost`, resolve any conflicts, test the code thoroughly, commit any needed changes to into  `issue12-Array-deleteRightmost`, and then push that branch back to Github?  Thanks.

**Comment by JMCanning78** [comment]
I made one small change, too.  I put the items being deleted into the `callEnviron` set so they would be cleaned up later.  If the user presses Stop before the animation finishes, they could remain on the canvas.

**Pull request merged**
