### PR TITLE
Why can't it merge?

### PR DESCRIPTION
**Pull request by NataniaBirnbaum**
Unsure

### CODE REVIEW

**Comment by JMCanning78** [comment]
What are you trying to accomplish?  Are you trying to merge `origin/master` into your issue branch  issue73-PriorityQueue?  
I think you can do that as long as you resolve the conflicts in  `PythonVisualizations/OrderedArray.py`.  Do you need some help with that?

**Comment by NataniaBirnbaum** [comment]
That's the thing - there aren't any conflicts. I copied and pasted the entirety of OrderedArray into the version on my branch just to be sure.

**Comment by JMCanning78** [comment]
The comment on commit aacc6007dfb265f38e2434a2e2be699bffd127e2 says "Ok never mind it works now".  Does that mean you solved the issue above?  It appears that PR #110 replaces this one.  If so, please close this PR (#109).  I will review PR #110.

**Comment by JMCanning78** [comment]
My mistake.  There's no need to close this PR, since it is marked as Merged.  That seems to have merged #109 into #110.

**Pull request merged**
