### PR TITLE
Issue31 circular array for queue

### PR DESCRIPTION
**Pull request by JMCanning78**
This draws the array holding the queue items as a circle to emphasize how the indices wrap around with modulo arithmetic. 

I put the front and rear index arrows inside the circle.  Keeping the labels and arrows from overlapping is rather hard.  I tried a couple of variations and ended up settling on using different colors and making the text label's center be the back end of the arrow.

This also implements the New function and Pause/Play/Stop, and enables the insertion of arbitrary strings as keys (up to 6 characters).

Note the different font sizes on Windows and macOS were problematic.  Getting settings that work on both means neither look great.

### CODE REVIEW

**Comment by JMCanning78** [comment]
After merging in changes from master, I had trouble pushing the modified Issue31-circular-array-for-queue branch back to github.  I had to force the push to get it to work.

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This looks great! I found one bug, had one specific thought, and a general aesthetic idea:

**Bug**
- if you press stop after pressing delete, the fill for the item disappears but nItems does not update and the pointers are confused.
Here are exact steps to reproduce:
1. Insert an item
2. Press delete
3. Press stop before the delete finishes
4. Press delete again

**Movement of front and rear labels and arrows**
- this may get fixed when you use `moveLinearly` (although I am not sure) but currently, the label moves first and then the arrow. The movement sequence seems a bit disjointed.
- this may not be worth the time, but the arrow is just redrawn. The movement of the arrow is not animated

**Background color**
- I noticed that the middle of the circular queue is white which contrasts the grey background. I think it would look nicer if the background color matched.
- As a general thought, perhaps all the animations should have a white background? I'm not sure if it would be look better, but it may

**Comment by JMCanning78** [comment]
The changes in the 4 commits leading up to commit ae49147 should address [your comments](https://github.com/JMCanning78/datastructures-visualization/pull/125#pullrequestreview-506986756) @lilypolonetsky.   I added a customized clean up routine to restore the pointers and nItems to their "correct" position and values with respect to the internal data structure state.  If the user stops an animation, the pointers will stop moving, but on the next operation, they are reset to their correct position before starting new animations.
I also merged in the changes in master so the pointers are now moving smoothly with moveItemsLinearly.  I added an explicit background color for all the Tk panels, so every background should be white except where we had other colors specified like the operation controls and code text windows.  The default background was different on macOS (white) vs Windows (gray).

**Review by lilypolonetsky — APPROVED** [review]
Looks great! The animation with the arrows is super smooth. I did not see any bugs

**Pull request merged**
