### PR TITLE
Issue15 SimpleSorting.py end-user tests

### PR DESCRIPTION
**Pull request by shirasassoon**
Michal and I worked on Issue #15 and some of our tests highlighted a few bugs that need to be reviewed and fixed.

### CODE REVIEW

**Comment by shirasassoon** [comment]
removed the comments with the end-user tests from SimpleSorting.py

**Comment by shirasassoon** [comment]
Placed the end-user tests in a different file called SimpleSorting-Test.py, put inside Test Results folder

**Comment by shirasassoon** [comment]
Merged `origin/master` branch into the issue15-test-simplesorting-end-user1 branch. Michal and I will repeat the tests.

**Comment by michalkaufman** [comment]
Shira Sassoon and I repeated the tests. There were no Tkinter exceptions thrown. Everything seems to be working properly except for an issue we found with stopping in the middle of an insertion sort. Below is a description of the issue (it appears in the test file):

During Insertion sort, the int stored as temp needs to be re-inserted into its correct position in the array, so specific ints in the array shift over to the right one by one to make room for it. When stop is clicked during a shift, the int being shifted which currently appears as a duplicate in the array remains a duplicate in the array. The int stored as temp remains above the array and will disappear when another animation is started. If stop is clicked at a moment when an int is shifting and one of the duplicates
is in a position in between boxes, the duplicate gets stuck in that position and will stay there during any subsequent animations.

**Pull request merged**
