### PR TITLE
Renaming SimpleQueue.py to Queue.py

### LINKED ISSUE #177: Rename SimpleQueue.py as Queue.py
It would be more consistent for users to have the name of file for the queue data structure be "Queue.py".  They would launch the visualization from the command line with `python3 Queue.py` and it would show up under Q's in the directory.  We switched to using SimpleQueue.py to make it easier for developers to work on it in certain IDE's.  I think the problem was that the IDE found Queue.py in the current working directory and imported that when it was trying to import the queue.Queue class from the standard library.  That might only be a problem on operating systems with case-insensitive file systems.

Once the development of the Queue visualization app is complete, the need for simple, consistent filenames outweighs the need for IDE compatibility.  At that point, just rename SimpleQueue.py to Queue.py.

### PR DESCRIPTION
**Pull request by JMCanning78**
This PR should close #177 if it eliminates problems in some IDE's or Python environments due to a name collision with the Queue class.

### CODE REVIEW

**Comment by JMCanning78** [comment]
I tested these changes by launching these 3 programs:

1. Queue.py
2. runAllVisualizations.py
3. AlgorithmVisualizations.py  (in the parent directory, datastructures-visualization)

These all ran properly in my Macintosh environment using the command line, PyCharm, and Wing Personal.  I configured both of the IDEs to use the same python3 executable as used on the command line.  I could enter an item in the queue, peek at it, and remove it.

 Natania, would you please try launching the programs in the Windows environment and report your findings?

**Comment by NataniaBirnbaum** [comment]
I tested Queue, runAllVisualizationsMenu, AlgorithmVisualizations, and runAllVisualizations in Wing 101, PyCharm, VSCode, IDLE, and the Windows command line.

Queue gave me no problems.

runAllVisualizationsMenu wouldn't run from command line for some reason. It has some problem with the findVisualizations function in allVisualizationsCommon. In other IDEs it gave me no problems.

AlgorithmVisualizations wouldn't run in VSCode until I got rid of the /usr/bin/env python3 statement at the top. In other IDEs it gave me no problems (even with the /usr/bin/env python3 statement).

runAllVisualizations (with the tabbed notebook) did give me problems. That program opens the window (except in command line, where it has the same problems as runAllVisualizationsMenu), allows the user to select a visualization and type in the argument box, but freezes and crashes as soon as an operation button is clicked. That happens in all the visualizations, not just Queue. Wing gave a traceback that leads me to believe it has something to do with the code window.

**Comment by NataniaBirnbaum** [comment]
> 
> 
> I tested Queue, runAllVisualizationsMenu, AlgorithmVisualizations, and runAllVisualizations in Wing 101, PyCharm, VSCode, IDLE, and the Windows command line.
> 
> Queue gave me no problems.
> 
> runAllVisualizationsMenu wouldn't run from command line for some reason. It has some problem with the findVisualizations function in allVisualizationsCommon. In other IDEs it gave me no problems.
> 
> AlgorithmVisualizations wouldn't run in VSCode until I got rid of the /usr/bin/env python3 statement at the top. In other IDEs it gave me no problems (even with the /usr/bin/env python3 statement).
> 
> runAllVisualizations (with the tabbed notebook) did give me problems. That program opens the window (except in command line, where it has the same problems as runAllVisualizationsMenu), allows the user to select a visualization and type in the argument box, but freezes and crashes as soon as an operation button is clicked. That happens in all the visualizations, not just Queue. Wing gave a traceback that leads me to believe it has something to do with the code window.

Command line error in runAllVisualizations.py (and runAllVisualizationsMenu.py):
Traceback (most recent call last):
  File "runAllVisualizations.py", line 189, in <module>
    showVisualizations(findVisualizations(args.files, args.verbose),
  File "C:\Users\Natania\Documents\GitHub\datastructures-visualization\PythonVisualizations\allVisualizationsCommon.py", line 41, in findVisualizations
    for filename in [f for f in files
  File "C:\Users\Natania\Documents\GitHub\datastructures-visualization\PythonVisualizations\allVisualizationsCommon.py", line 42, in <listcomp>
    if isPatternInFile(runVizCallPattern, f)]:
  File "C:\Users\Natania\Documents\GitHub\datastructures-visualization\PythonVisualizations\allVisualizationsCommon.py", line 88, in isPatternInFile
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

Wing error for runAllVisualizations.py:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Natania\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "c:\Users\Natania\Documents\GitHub\datastructures-visualization\PythonVisualizations\VisualizationApp.py", line 692, in resizeCodeText
    ct['width'] = desired
  File "C:\Users\Natania\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1648, in __setitem__
    self.configure({key: value})
  File "C:\Users\Natania\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Natania\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1622, in _configure
    cnf = _cnfmerge(cnf)
  File "C:\Users\Natania\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 103, in _cnfmerge
    if isinstance(cnfs, dict):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by JMCanning78** [comment]
I think commit 2c5481d will solve the `FileNotFoundError: [Errno 2] No such file or directory` error mentioned in [your comment above](https://github.com/JMCanning78/datastructures-visualization/pull/251#issuecomment-893873678).

The `RecursionError: maximum recursion depth exceeded while calling a Python object` is a different problem.  It has to do with window resizing and figuring out what size the codeText window should be.  I'll see if I can reproduce the problem on my Windows box.

**Comment by JMCanning78** [comment]
I think commit e4fb616 will fix the freeze-up and  `RecursionError`.  Try it out in your environment and see.

**Comment by NataniaBirnbaum** [comment]
The RecursionError and FileNotFoundError are both fixed and all the files run as they are supposed to from my IDEs.

**Review by NataniaBirnbaum — APPROVED** [review]

**Pull request merged**
