### PR TITLE
Issue102: Add more algorithm visualizations

### PR DESCRIPTION
**Pull request by JMCanning78**
This implements Issue #102 and also cleans up some lingering files in the __pycache__ directory.  I have added `__pycache__/` to the `.gitignore` file to hopefully prevent other cached files from creeping in.

### CODE REVIEW

**Comment by JMCanning78** [comment]
Another visible change in this PR, when AlgorithmVisualizations.py is launched, it adds a status line at the bottom of the Introduction tab.  The status line reports how many of the visualization modules have been loaded.  The first four load in the blink of an eye, but the fifth, the SkipList, takes several seconds (at least on my computer).  The other modules are functional while that loading goes on.  The status line is erased once all the modules are loaded and the tabs are added to the notebook.

**Comment by EstherWerblowsky** [comment]
Question about reviewing this pull request- If i noticed something that I am confused about/ looks like it can be fixed within each visualization should I comment or request a change for it? Or should I leave it alone?

**Comment by JMCanning78** [comment]
It's hard answer [your question](https://github.com/JMCanning78/datastructures-visualization/pull/111#issuecomment-663327926) without know the nature of the problem.  Creating an Issue might be good.  There could be a discussion there about whether what you found is a bug or not and how to fix it.  Just describing it in this PR might serve the same purpose as opening up a new issue.  As for leaving it alone, that's up to your judgement.  I don't think there's any harm in discussing ideas that might improve the visualizations.

**Comment by EstherWerblowsky** [comment]
Ok so here are a few things that I have noticed with the visualizations that I either were just not consistent across the visualization or I thought that possibly they can be improved. Any ideas/discussion is welcome.

- in the Array visualization: When clicking delete rightmost in an empty array- no error message appears. This is different than ordered array for which the error message does appear

- also in the Array visualization: when traversing an empty list- the square shows up and there is nothing happening. I wasn't sure but would love feedback about that- if its intentional or maybe it can be disabled for an empty array...?

- In the simple sort: when the list is empty, instead of the sort not being allowed - the code and associated arrows show up anyways. Is that intentional? Or perhaps would it look neater if the sorts were not allowed for an empty list and error message appears?

**Comment by JMCanning78** [comment]
Regarding the 3 potential issues [@EstherWerblowsky cites](https://github.com/JMCanning78/datastructures-visualization/pull/111#issuecomment-664071290)

- I get an error message when running Delete Rightmost for both Array and OrderedArray.  I could not repeat the issue of not getting an error message.

- In the use of the data structure, traversing an empty array does almost nothing.  It enters the traverse routine, determines there are no items, and returns.  That's pretty much what the visualization shows.  It's not an error to traverse an empty array, so I don't think we should tell the user an error has occurred.

- Regarding sorting empty arrays (or even arrays with one element), it's very similar to traversal.  Running the sort does nothing except call a routine that exits quickly.  It's not an error, like asking for the first element of an empty data structrue, but it doesn't achieve anything other than using up some compute time.  I think the visualization in its current form is fine.

**Pull request merged**
