### PR TITLE
nItems pointer 2.0

### PR DESCRIPTION
**Pull request by ShaniLewis**
issue #67 
Shira Schneider and I added a nitems pointers to Array.py, SimpleSorting and OrderedArray, please see Pull Request #69 for more information.

### CODE REVIEW

**Comment by ShaniLewis** [comment]
@JMCanning Did you want us to have the nItems pointer move before an item is visually removed in the delete function as well (in addition to the delete right-most)?

**Comment by ShaniLewis** [comment]
Shira and I just updated the branch nItemsPointer-#2 to be compatible with the current master. If it all looks good, we believe it is ready to be officially merged :)

**Comment by JMCanning78** [comment]
There are still the two problems mentioned in [my last comment](https://github.com/JMCanning78/datastructures-visualization/pull/113#pullrequestreview-454579545).  I'll repeat here in checklist form:

- [ ]  In Array.py, the `nItems` pointer is not being moved on the canvas when the code changes it during a Delete operation.  It should be decremented *before* items are shifted to the left in the array.
- [ ]  In OrderedArray.py, the `nItems` pointer is not being moved on the canvas when the code changes it during a Delete operation.  It should be decremented after the call to `search()` successfully finds the item to remove and  *before* items are shifted to the left in the array.
- [ ] In OrderedArray.py, the operation buttons are not returning to their normal status after a Delete operation.  The Pause and Stop buttons remain enabled but should be disabled.  The operations taking an argument are not re-enabled when numbers are entered in the text entry area.  This is probably due to an imbalance of calls to `createCallEnvironment()` and `cleanUp(callEnviron)`.  Each call environment needs to be cleaned up by the method that created it.  I think that's not always happening for some calls to `search()`.  If the clean up doesn't happen, VisualizationApp thinks the animation is still running and doesn't set the buttons statuses corrrectly.

**Comment by ShiraSchneid** [comment]
Shani and I updated this code. The nItems pointer now moves before the items are shifted, and we also fixed the problem with the buttons. Additionally, we noticed that the red circle was not removed as items were shifted over, so we added a remove in search() in orderedArray

**Review by JMCanning78 — APPROVED** [review]
Those changes look good.  I made some additional changes, however, as follows in commit 98fda57:

- Fixed extraction of 'fill' configuration setting for cell background color.
- Changed `removeFromEnd()` animation to be consistent across all 3 visualizations, including leaving removed items in the `callEnviron` to be cleaned up after moving off canvas.
- Removed redundant definitions of `enableButtons()`, `startAnimations()`, and `stopAnimations()` since the versions in VisualizationApp.py handled everything.
- Removed unneeded calls to `stopAnimations()`and `update()` since the  `cleanUp()` method already handles that.
- Removed a redundant loop creating array cells in the `newArraySize()` method of OrderedArray.py
- Changed how the found circle is removed in the `search()` method of OrderedArray.py.  I left the found circle in the `callEnviron` so that it would be cleaned up with other temporary items when removed from the call stack (see below).
- Changed the animation in the `remove()` method of OrderedArray.py so that a found item is moved off the canvas prior to decrementing the `nItems` pointer and shifting items to the left in the array.  This allowed removal of a waiting period with no animation after finding the item to remove.
- Removed the creation of an unneeded call environment in the `display()` method of SimpleSorting.py

I can see that the functioning of `createCallEnvironment()`, `startAnimations()`, `stopAnimations()`, `enableButtons()`, `cleanUp()`, and `window.update()`  is difficult to follow.  I think people understand the concept of the temporary variables and the need to remove them after an animated operation, but knowing when to use each of those methods is hard to understand.  Perhaps I should write a guide on their use for all the collaborators.

**Pull request merged**
