### PR TITLE
Update and rename realStack.py to Stack.py

### PR DESCRIPTION
**Pull request by shirapahmer**
Switched the old RealStack.py code and replaced it with the new Stack.py code that has a Push and Pop method, and an arrow pointing to the top of the stack

### CODE REVIEW

**Comment by JMCanning78** [comment]
There are many pull requests linked to Issue #29.  In https://github.com/JMCanning78/datastructures-visualization/pull/59#pullrequestreview-439352638 I requested that this PR be revised to rename realStack.py into Stack.py.  If that's not accomplished by one of the other related PR's, we may still need to do it here.

**Comment by shirapahmer** [comment]
This pull request was what we did with the Renaming a File on github.com. We followed the instructions for how to rename a file, but then we got rid of the old code that was in the file originally and replaced it with our updated Stack.py code because we didn't want the file to be called Stack.py but contain the old code from realStack.py. Was there something else we were supposed to do?

**Comment by JMCanning78** [comment]
Regarding @shirapahmer's comment https://github.com/JMCanning78/datastructures-visualization/pull/59#issuecomment-653047090 , when I look at the Files changed for this PR and PR #63, I see realStack.py is deleted and Stack.py is added.  I don't see realStack.py renamed as Stack.py.  If you did "the Renaming a File on github.com" as you mentioned, and pushed those commits onto this issue branch, shirapahmer-patch-1, then they should show up in this PR.  Do you see a commit in the history of one the issue branches that shows renaming the file?  If you do see that, please send me the commit tag (the 40-character hexadecimal string identifying the commit).  Github Desktop shows a right pointing arrow for a file renaming operation.  It uses minus symbols for deletions and plus symbols for additions.
Screen Shot 2020-07-02 at 1 04 42 PM

Github.com also shows it that way (see https://github.com/JMCanning78/datastructures-visualization/pull/51/files for an example).   I can meet with you and go over the renaming process if you like.

**Comment by JMCanning78** [comment]
Closed by PR #63

**Pull request closed without merging**
