### PR TITLE
Issue137 create infix calcluator

### LINKED ISSUE #137: Construct InfixCalculator visualization
This visualization is different than the data structure visualizations; it shows an application that makes use of stacks and queues to evaluate expressions.  The one operation takes a infix expression, translates it to postfix form, and then evaluates it to get a result.  This will animate the `PostfixTranslate()` and `PostfixEvaluate()` functions shown in Chapter 4, Stacks and Queues (and copied below).

There is a lot of data to show on the canvas.   `PostfixTranslate()` has a stack and a queue  and `PostfixEvaluate()` has its own stack.  These should be placed so they don't overlap and can be on the screen at the same time (even though `PostfixTranslate()` exits before `PostfixEvaluate()` starts).  They both call `nextToken()` to get the next token to process, so we need a place on the canvas for the string being processed there.

Here's a potential layout of the various data structures:
Screen Shot 2020-09-28 at 4 31 08 PM
The box at the top would show the string being be processed by `nextToken()`.  Initially that's the input in-fix expression and later it's the post-fix result of `PostfixTranslate()`. We could use the same box for both strings changing the label at the left from "Infix" to "Postfix" and perhaps the color of the box's background to indicate the change in meaning.  That would save space, but if there's enough space, then putting the postfix expression below the infix one would more faithfully represent the operations.

The stacks and the string parameter of the three functions are all named `s` which is confusing in the visualization.  If there's time to modify the textbook code, `PostfixTranslate()` should rename the stack to `inStk' and `PostfixEvaluate()` should rename its stack to `postStk`.  This will require changes to the text, so we need to wait on that.

The potential layout above shows an intermediate state that would not occur in the processing of the expression.  The infix expression would be shortened as tokens are pushed on the stack and inserted on the queue.  The stack for `PostfixEvaluate()` is only created after getting the output from `PostfixTranslate()`, and the final output box would only show up after that.  The stack and queue for  `PostfixEvaluate()` should disappear after the translation is done (they will both be empty then).  The layout is intended to propose where the  various items would be displayed.

The animation would:
1. Create the infix string box, the stack and queue for the `PostfixTranslate()` function.
1. Copy the input string from the operations text entry box to the infix string box .
1. Process the tokens from the string, pushing operators on the stack and inserting operands and operators into the queue.
1. Remove items from the queue to form the postfix expression placing in the postfix string box.
1. Create the stack for the `PostfixEvaluate()`  function.
1. Process the postfix string box, pushing operands on the stack and applying operators to combine them.
1. Copy the final stack item to the output box.

This is a long animation and should go fairly fast.  That will allow someone to run it fast to skip over an early part then pause at the steps of interest.  If an error occurs in the program (from a problem in the input expression), the stack and queue contents should remain on the canvas and error message should appear in the status line.

The queue should probably have a different appearance than the stack.  There's probably not enough space for the circular array form used in the SimpleQueue.py visualization, but perhaps some changes in color and outlining would be good enough.  With the queue being shown vertically, the labels for `front` and `rear` would need to be placed so they don't overwrite one another when pointing at the same cell.

There could be some opportunity to make parent classes for stacks and queues that could be reused in the Stack.py, Graphs.py, and WeightedGraphs.py visualizations.

Here is the textbook source code for PostfixTranslate.py
```
operators = ["|", "&", "+-", "*/%", "^", "()"]
def precedence(operator):  # Get the precedence of an operator
    for p, ops in enumerate(operators):  # Loop through operators
        if operator in ops:              # If found,
            return p + 1                 # return precedence (low = 1)
        # else not an operator, return None
        
def delimiter(character):  # Determine if character is delimiter
    return precedence(character) == len(operators)

def nextToken(s):          # Parse next token from input string
    token = ""             # Token is operator or operand
    s = s.strip()          # Remove any leading & trailing space
    if len(s) > 0:         # If not end of input
        if precedence(s[0]):  # Check if first char. is operator
            token = s[0]   # Token is a single char. operator
            s = s[1:]
        else:              # its an operand, so take characters up
            while len(s) > 0 and not (   # to next operator or space
                    precedence(s[0]) or s[0].isspace()):
                token += s[0]
                s = s[1:]
    return token, s  # Return the token, and remaining input string

def PostfixTranslate(formula): # Translate infix to Postfix
    postfix = Queue(100)       # Store postfix in queue temporarily
    s = Stack(100)             # Parser stack
    
    # For each token in the formula  (fencepost loop)
    token, formula = nextToken(formula)
    while token:
        prec = precedence(token)  # Is it an operator?
        delim = delimiter(token)  # Is it a delimiter?
        if delim:
            if token == '(':      # Open parenthesis
                s.push(token)     # Push parenthesis on stack
            else:                 # Closing parenthesis
                while not s.isEmpty():  # Pop items off stack
                    top = s.pop()
                    if top == '(':      # Until open paren found
                        break
                    else:               # and put rest in output
                        postfix.insert(top)
                        
        elif prec:                # Input token is an operator
            while not s.isEmpty():  # Check top of stack
                top = s.pop()
                if top == '(':      # If open parentheis,
                    s.push(top)     # push it back on stack and
                    break           # stop loop
                else:               # Else top is an operator
                    if precedence(top) >= prec: # and higher prec.
                        postfix.insert(top) # then output it
                    else:           # Stop at lower prec. operator
                        s.push(top)
                        break
            s.push(token)         

        else:                     # Input token is an operand
            postfix.insert(token) # and goes straight to output
        
        token, formula = nextToken(formula) # Fence post loop
    
    while not s.isEmpty():       # At end of input, pop stack
        postfix.insert(s.pop())  # operators and move to output

    ans = ""
    while not postfix.isEmpty(): # Move postfix items to string
        if len(ans) > 0:
            ans += " "           # Separate tokens with space
        ans += postfix.remove()
    return ans
```

Here is the textbook source code for PostfixEvaluate().  Note the `print` statements don't need to be in the animation.  Also changing the `s.push(int(token))` to `s.push(eval(token))` will allow the calculator to process floating point numbers.  For the first implementation, let's stick with what's in the book.
```
def PostfixEvaluate(formula):  # Translate infix to Postfix and
                               # evaluate the result

    postfix = PostfixTranslate(formula) # Postfix string
    s = Stack(100)                      # Operand stack
    
    token, postfix = nextToken(postfix)
    while token:
        prec = precedence(token)  # Is it an operator?

        if prec:                  # If input token is an operator
            right = s.pop()       # Get left and right operands
            left = s.pop()        # from stack
            if token == '|':      # Perform operation and push
                s.push(left | right)
            elif token == '&':
                s.push(left & right)
            elif token == '+':
                s.push(left + right)
            elif token == '-':
                s.push(left - right)
            elif token == '*':
                s.push(left * right)
            elif token == '/':
                s.push(left / right)
            elif token == '%':
                s.push(left % right)
            elif token == '^':
                s.push(left ^ right)
                
        else:                    # Else token is operand
            s.push(int(token))   # Convert to integer and push
            
        print('After processing', token, 'stack holds:', s)
        
        token, postfix = nextToken(postfix) # Fence post loop

    print('Final result =', s.pop()) # At end of input, print result
```

### PR DESCRIPTION
**Pull request by JMCanning78**
This PR should close #137 by creating the InfixCalculator.py app.  This is a little different from some of the other visualization applications in that it is not for a single data structure.  It demonstrates the operation of two stacks and one queue in converting infix to postfix and then evaluating the postfix expression.

### CODE REVIEW

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This looks amazing! A couple of small comments:
1. When I first tried using the visualization, I could not figure out how to restart the visualization while it was underway. After some experimentation, I figured out that you just need to delete the expression you had typed. While operational, I think this may be a confusing user interface. I think it could work as is if it is explained in the textbook but definitely something to think about.
2. The animation of the movement of each item from the translate queue to postfix is moving from the box above it.
3. I got the following error when trying to use the & operand on a float and an int. This may be expected behavior, but it was unclear to the user why the program had crashed.
4. Float and int can't have & operand applied
```
  File "c:/Users/lilyp/Documents/LAVA/datastructures-visualization/PythonVisualizations/InfixCalculator.py", line 420, in PostfixEvaluate
    L&R if check('&') else
TypeError: unsupported operand type(s) for &: 'float' and 'int'
```
5. I tried having it evaluate 5^100 and it returned 97
6. There is no max number so if you give it a really long number, the number does not fit in the queue

**Comment by JMCanning78** [comment]
Thanks for finding to time to review this, Lily.  I hadn't really thought much about the error conditions.  I think it's important 1) not to have the app crash, and 2) show something that indicates processing is continuing but it has found some error in evaluating the expression.  Commit da7605f should address points #3 and #4 in [your review](https://github.com/JMCanning78/datastructures-visualization/pull/176#pullrequestreview-560601630).  Since some beginners might think that 6 / 3 evaluates to 2 instead of 2.0 in Python, I made it so if it catches a type error, it tries converting both operands to integers and then apply the operator.  That doesn't reflect the reality in a computer, but I think the risk is low that they take away that it works the same as the // operator.

Users will see error messages for division by zero (e.g.  4 / 0, 4 % 0) and missing operands (e.g.  4 +).  If those errors are embedded within a longer expression, it will keep evaluating the expression but carry the error through to the end.

On the other points:
#1  I think that the purpose of the Stop button has been made clear in many of the previous apps.  If the user happened to start with this one and didn't know that to stop the evaluation they had to press Stop, I don't think that's a big enough problem to make a change to this app.  To restart, they would press Evaluate again.   I'm not sure what else we could do to better communicate that.  There are hints shown if the user lets the mouse hover over the buttons.

#2 I couldn't get the behavior you mention: "The animation of the movement of each item from the translate queue to postfix is moving from the box above it", or maybe I didn't understand what you meant.  I do see the animation moving the item indexed by the `front` arrow on each cycle of the loop that empties the Translate queue.  When you say "above it", did you mean above the cell indexed by `front`?

#5 You saw the correct result, 5^100 is 97.  The caret operator, ^, is bit-wise exclusive-OR in Python (not the power operator, i.e., 5**100)

#6 Really long numbers are a problem.  If you make a fraction like 1 / 3, it will write 0.33333333333 which doesn't fit easily anywhere.  Since there's no power operator it's a bit harder for users to create big integers without typing all the digits.  The point of the app is to demonstrate the use of stacks and queues, so the interesting issues that happen with numbers that can't be displayed in a few characters are tangential.  I suppose we could erase the Translate stack and queue and then make the Evaluate stack wide enough to handle 15 digit numbers, but I think there are more important problems to solve.

**Review by lilypolonetsky — CHANGES_REQUESTED** [review]
This looks great! The error handlers do a great job of catching any conversions that are needed.

In regards to the animation I had mentioned in comment #2, I uploaded a video here to demonstrate the behavior. Watch as the item moves from the index above its current place in the translate queue to the ans area.

https://user-images.githubusercontent.com/36013651/103487842-47ed3480-4dd6-11eb-8876-036d12e52ffb.mp4

**Comment by JMCanning78** [comment]
You have a very good eye for small details!  The animation actually started with the front queue item shifted over to the right a little bit.  As it moved towards the `ans` string, its path crossed the item in the cell above it, so it looked like it was coming from there.  Commit 550fa05 changes that so it should start directly on top of the front queue item.

**Review by lilypolonetsky — APPROVED** [review]
Looks great to me!

**Pull request merged**
